### PR TITLE
Implementing Selectable , accordion , autocomplete

### PR DESCRIPTION
**Pull request by percyashu**
Please check

### CODE REVIEW

**Review by Ifeanyijasper — COMMENTED** [review]
Commit message does not align with these files.

**Review by Ifeanyijasper — COMMENTED** [review]
Why all your changes are commented. Especially the tab2 and tab3 of all the modules you worked on

**Comment by percyashu** [comment]
They don't work.  I had difficulties in doing them.

**Comment by Ifeanyijasper** [comment]
Use try and except in the code. The except should print the error you are experiencing in the code.
I think  @xurror should also modify his code where necessary with respect to these changes. This will act as help in reporting bugs. We are testing website not our code

**Comment by percyashu** [comment]
Its complete now
review

**Comment by percyashu** [comment]
It was failing with Message: move target out of bounds
  (Session info: chrome=79.0.3945.88)

**Comment by xurror** [comment]
I wan to trust this is ok

**Comment by xurror** [comment]
You so seriously did this from master branch

**Pull request closed without merging**
